version: "3.8"
services:
    client:
        image: Sniffer/yolo-client:1.0
        build:
            context: .
            dockerfile: FrontEnd.dockerfile
        ports: 
            - 3000:3000
    backend: 
        image: Sniffer/yolo-backend:1.0
        build: 
            context: .
            dockerfile: BackeEnd.dockerfile
        ports: 
            - 5000:5000
        depends_on: 
            -mongo
    mongo:
        image: mongo
        ports: 
            -27017:27017
